[package]
name = "vertigo"
version = "0.1.0"
authors = ["Carles Pey <carles.pey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
regex = "1.5.4"
itertools = "0.9.0"
structopt = "0.3.23"
